heading_controller:
  ros__parameters:
    sailbot:
      heading_control:
        rudder_adjustment_scale: 1.0
        rudder_overshoot_bias: 10.0
        vector_field_crosstrack_weight: 1.0
        vector_field_path_dir_weight: 1.0
        leeway_correction_limit_degrees: 10.0
        wind_restriction_replan_cutoff_degrees: 30.0

heading_select:
  ros__parameters:
    sailbot:
      heading_select:
        use_camera_heading: False
    
esp32_comms:
  ros__parameters:
    sailbot:
      rudder:
        angle_limit_deg: 30

path_follower:
  ros__parameters:
    sailbot:
      pathfinding:
        buoy_rounding_distance_meters: 10.0
        buoy_threat_size_map_units: 2.0
        buoy_threat_guassian_intensity: 0.2
        min_path_recalculation_interval_seconds: 10.0
      navigation:
        look_ahead_distance_meters: 3.0
        look_ahead_increase_per_knot: 1.0
        buoy_snap_distance_meters: 10.0

wind_smoother:
  ros__parameters:
    sailbot:
      num_true_wind_readings: 20
      num_apparent_wind_readings: 10


buoy_detection:
  ros__parameters:
    sailbot:
      cv:
        buoy_circularity_threshold: 0.6
        depth_error_threshold_meters: 1.0
        buoy_detection_lifetime_seconds: 3.0

network_comms:
  ros__parameters:
    sailbot:
      cv:
        buoy_circularity_threshold: 0.6
