heading_controller:
  ros__parameters:
    sailbot:
      heading_kp: 0.5
    
esp32_comms:
  ros__parameters:
    sailbot:
      rudder:
        angle_limit_deg: 30

path_follower:
  ros__parameters:
    sailbot:
      pathfinding:
        buoy_rounding_distance_meters: 5.0
        buoy_threat_size_map_units: 2.5
        buoy_threat_guassian_intensity: 0.7
        min_path_recalculation_interval_seconds: 10.0
      navigation:
        look_ahead_distance_meters: 3.0
        look_ahead_increase_per_knot: 1.0
        buoy_snap_distance_meters: 10.0

wind_smoother:
  ros__parameters:
    sailbot:
      num_wind_readings: 20